---
Name: socialmeta
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - Innoweb\SocialMeta\Extensions\SiteTreeExtension
  title_divider: ' - '
  metadata_tab_enabled: true
  metadata_tab_name: 'Root.Metadata'
  meta_description_fallback_fields:
    - Content
  meta_description_fallback_to_site: true
  include_site_jsonld: 'home'

SilverStripe\Security\Member:
  extensions:
    - Innoweb\SocialMeta\Extensions\AuthorExtension

Page:
  socialmeta_opengraph_type: 'article'

Innoweb\SocialMeta\Extensions\SiteTreeExtension:
  image_size_twitter:
    width: 1024
    height: 512
  image_size_opengraph:
    width: 1200
    height: 628
  minify_jsonld: true

---
Name: socialmeta-multisites
Only:
  moduleexists: 'symbiote/silverstripe-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialMeta\Extensions\MultisiteCurrentConfigSiteConfigExtension
Symbiote\Multisites\Model\Site:
  extensions:
    - Innoweb\SocialMeta\Extensions\ConfigExtension
    - Innoweb\SocialMeta\Extensions\MultisiteSiteExtension
  socialmeta_root_tab_name: 'Root.Metadata'

---
Name: socialmeta-configured-multisites
Only:
  moduleexists: 'fromholdio/silverstripe-configured-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialMeta\Extensions\ConfiguredMultisiteCurrentConfigSiteConfigExtension
Fromholdio\ConfiguredMultisites\Model\Site:
  extensions:
    - Innoweb\SocialMeta\Extensions\ConfigExtension
    - Innoweb\SocialMeta\Extensions\ConfiguredMultisiteSiteExtension
  socialmeta_root_tab_name: 'Root.Metadata'

---
Name: socialmeta-nomultisites
Except:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
    - 'fromholdio/silverstripe-configured-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Innoweb\SocialMeta\Extensions\CurrentConfigSiteConfigExtension
    - Innoweb\SocialMeta\Extensions\ConfigExtension
  socialmeta_root_tab_name: 'Root.Metadata'
